### ISSUE TITLE
添加特定屏蔽词功能

### ISSUE THREAD

**Issue by LsrlYrsc** [CikeyQi/mc-plugin#11]
如题
比如:blacklist:§;1;2，这如果有此类文字便略过发送
实际情况:plugins(xx):<del>§</del>xxxx
<del>看一眼plugins简直等于是要自己的命</del>

**Comment by CikeyQi** [comment]
这是颜色符号，请问预期的结果与实际结果分别是什么呢？

**Comment by LsrlYrsc** [comment]
颜色符号在QQ聊天里面是直接显示出来的
我想为了更好的观看性尽量地可以自定义去除一些看着难受的东西

**Comment by LsrlYrsc** [comment]
在QQ里面的结果应该是过滤掉黑名单里面的字/符号之后然后再发送到QQ聊天里

**Comment by CikeyQi** [comment]
能举个例子吗，这将方便我们选择更正确的解决方法

**Comment by LsrlYrsc** [comment]
> 能举个例子吗，这将方便我们选择更正确的解决方法

原本情况:§4你好
添加§为黑名单后情况:4你好

**Comment by CikeyQi** [comment]
§4是一个颜色符号呀，表示的是深红色，你确定只需要移除§符号吗？

**Comment by LsrlYrsc** [comment]
> §4是一个颜色符号呀，表示的是深红色，你确定只需要移除§符号吗？

我希望这个可以自定义黑名单的，这样就可以自由地添加屏蔽词
§4是个颜色符号没错，但他类似的符号配合在QQ里面使用rcon指令是显示出来的，所以我想屏蔽这个符号(顺带后面的颜色代号去掉更好)

**Comment by CikeyQi** [comment]
那我将使用正则表达式进行匹配删除，如：/§./g，这将匹配§与其后面的一个字符

**Comment by CikeyQi** [comment]
这个正则表达式将需要用户手动添加

**Comment by LsrlYrsc** [comment]
> 那我将使用正则表达式进行匹配删除，如：/§./g，这将匹配§与其后面的一个字符

👍

**Comment by LsrlYrsc** [comment]
> 这个正则表达式将需要用户手动添加

好
