### ISSUE TITLE
群聊消息始终无法传到服务器

### ISSUE THREAD

**Issue by RyanJiang184** [CikeyQi/mc-plugin#15]
使用插件端：
【MCserver的配置】:
enable_mc_qq: true
........

【server properties配置】:
rcon.port=25575
rcon.password=***
enable-rcon=true

【mc-plugin配置】:
mc_qq_ws_url: /yz/v3/mcqq
mc_qq_ws_port: 9090
mc_qq_send_group_name: false
rcon_enable: true
rcon_host: (服务器公网ip)
rcon_port: 10005(内网25575映射到公网端口)
group_list:
  - ******
rcon_password: ***
command_header: /

【群聊响应】：
可以正常的收到服务器的信息并发送到qq群

【服务器响应】：
无响应

【TRSS报错日志】：
[TRSSYz][21:30:02.930][ERRO] 【Minecraft-Plugin v1.0.1】 Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by CikeyQi** [comment]
群聊消息是通过rcon连接传输到服务器的，根据报错信息初步断定rcon连接出现问题，根据您的反馈信息，rcon_host应为映射服务器公网IP地址，并检查端口是否打开，若仍无法解决问题请进QQ群与我取得联系
