### ISSUE TITLE
使用shamrock无法发送消息到QQ

### ISSUE THREAD

**Issue by Fahaxikiii** [CikeyQi/mc-plugin#22]
![image](https://github.com/CikeyQi/mc-plugin/assets/93320886/46164fae-8d9c-4d21-a368-648f558960c2)

**Comment by CikeyQi** [comment]
你所使用的适配器是？

**Comment by Fahaxikiii** [comment]
> 你所使用的适配器是？

https://gitee.com/Zyy955/Lain-plugin用的这个插件，Shamrock

**Comment by CikeyQi** [comment]
该适配器已有类似的issues∶https://github.com/Zyy955/Lain-plugin/issues/19

**Comment by Fahaxikiii** [comment]
> 该适配器已有类似的issues∶[Zyy955/Lain-plugin#19](https://github.com/Zyy955/Lain-plugin/issues/19)

好的，感谢
