### ISSUE TITLE
QQ群的信息无法同步到游戏服务器内

### ISSUE THREAD

**Issue by Pawsedawa** [CikeyQi/mc-plugin#27]
服务端 1.20.4 leaves
rcon没问题 因为可以在Q群发送指令
后来查看日志发现
tellraw @a {"text":"","extra":[{"text":"Q群信息","color":"white","bold":"false"}]}
这串指令根本无法在mc服务端运行
后来发现问题出现在"bold":"false"中
将false的引号去掉后就可以执行了

**Comment by CikeyQi** [comment]
我参考Minecraft Wiki发现如下内容：

指定要发送的消息。必须是有效的JSON文本（例：'{"text":"Hi there!","bold":"true"}'[仅Java版]）

带双引号的布尔值才是正确的命令格式，请参考[Minecraft Wiki](https://minecraft.fandom.com/zh/wiki/命令/tellraw)

**Comment by Pawsedawa** [comment]
问题是我现在是布尔值加了引号就无法在服务端使用 不加引号就能正常使用 我该怎么解决这个恼人的问题

**Comment by Pawsedawa** [comment]
![86C4A214-18F8-4D09-A273-B9F41C8DA889](https://github.com/CikeyQi/mc-plugin/assets/110442707/4989fb66-fddc-42e1-8cfc-47c3a0f2dff8)

**Comment by CikeyQi** [comment]
![image](https://github.com/CikeyQi/mc-plugin/assets/61369914/aba390d7-6363-41eb-8e47-98a51ca0cf07)

在我的Minecraft版本中它是正常的，若有更多人反馈这个问题，我再考虑将代码更改，在此之前请自行修改代码使用
