### ISSUE TITLE
ws怎么弄？

### ISSUE THREAD

**Issue by Yummy-cookie** [CikeyQi/mc-plugin#31]
ws怎么弄？

**Comment by Yummy-cookie** [comment]
fabric

**Comment by CikeyQi** [comment]
去 [Releases](https://github.com/CikeyQi/mc-plugin/releases) 下载 fabric 端的 mod，服务器安装后按照 README.md 教程配置，插件这边用 Guoba-Plugin 配置

**Comment by Yummy-cookie** [comment]
1.20.4怎么办

**Comment by Yummy-cookie** [comment]
没事了
