### ISSUE TITLE
希望能自定义RCON消息的前缀

### ISSUE THREAD

**Issue by CuteLittleSky** [CikeyQi/mc-plugin#32]
![image](https://github.com/CikeyQi/mc-plugin/assets/62592731/58f33ab9-8b98-4ac9-a6f5-e888b898f0ac)
就是图片这里的
要不需要改js里的会影响更新= =

**Comment by CikeyQi** [comment]
没理解什么意思

**Comment by CuteLittleSky** [comment]
> 没理解什么意思

![image](https://github.com/CikeyQi/mc-plugin/assets/62592731/22ef5ac4-c0a9-4108-8b1a-25167e25a67c)
就是能自己修改发送回服务器的聊天JSON信息,便于和服务器内统一


另外每次重启服务器之后群到服务器RCON信息就发不过去了,必须重启喵崽才行..

**Comment by CikeyQi** [comment]
- 关于你提到的自定义消息样式，我感觉这个功能不是必须，且没想到好的方法实现，所以暂时没有做的想法
- 关于提到的重启服务器后RCON信息发不过去的问题，RCON断开后插件会尝试3次连接（这个次数可以在配置文件修改），如果仍然连接失败就需要重启机器人时才会主动连接
