### ISSUE TITLE
游戏服务器发送的消息没有同步到QQ群

### ISSUE THREAD

**Issue by ayakasuki** [CikeyQi/mc-plugin#9]
![image](https://github.com/CikeyQi/mc-plugin/assets/20859971/28cb44d5-210f-496d-89a5-aa63ebb2f6eb)
![image](https://github.com/CikeyQi/mc-plugin/assets/20859971/8a495338-64bc-49d3-91aa-40fe46e743fd)
![image](https://github.com/CikeyQi/mc-plugin/assets/20859971/fd24b103-325a-4c2e-9c27-28473f944173)
如图

**Comment by ayakasuki** [comment]
是fabric端来着 但是QQ群的消息能发送到服务器

**Comment by ayakasuki** [comment]
在想是不是没移植mcqq_tool来着 我nonebot端容易断 所以想用yz来用这个mctool移植版来着

**Comment by CikeyQi** [comment]
Fabric端适配可能有问题，我无法复现环境，希望能在QQ群与我取得联系，以方便我调试

**Comment by CikeyQi** [comment]
#10
